blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:login'), name='logout'),
    path('posts/', views.HomeView.as_view(template_name='home/index.html'), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(template_name='home/post.html'), name='post_detail'),
    path('register/', views.SignUpView.as_view(template_name='home/register.html'), name='register'),
    path('posts/new/',views.CreatePostView.as_view(template_name='home/post_form.html'), name='create_post'),
    path('post/<int:pk>/update', views.EditPostView.as_view(template_name='home/post_form.html'), name='edit_post'),
    path('post/<int:pk>/delete', views.DeletePostView.as_view(template_name='home/post_confirm_delete.html'), name='delete_post'),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name='about'),
    path("contact-us/", views.ContactView.as_view(), name='contact'),


]



djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=300, blank=False, null=False)
    description = models.TextField(max_length=300, blank=False, null=False,)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    comment = models.ManyToManyField('Comment', related_name='post', blank=True)
    image = models.ImageField(upload_to='images', blank=True, null=False, default='default.jpg')

    class Meta:
        ordering = ['-created_at', '-updated_at']

    def get_absolute_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.CharField(max_length=400, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # class Meta:
    #     ordering = ['-created_at', '-updated_at']


    def __str__(self):
        return f"user {self.owner} commented: {self.body}"

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Comment
from ckeditor.widgets import CKEditorWidget



class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

#
# class UpdatePost(forms.ModelForm):
#     description = forms.CharField(widget=CKEditorWidget)
#     class Meta:
#         model = Post
#         fields = ['title', 'description', 'image']


class CreateUpdatePost(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title', 'description', 'image']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields= ['body']


blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Comment
import os


# Create your views here.
class SignUpView(SuccessMessageMixin, CreateView):
    form_class = forms.SignUpForm
    success_url = reverse_lazy('blog:login')


class HomeView(ListView):
    model = Post


class PostDetailView(View):
    model = Post
    template_name=None

    def get(self, request, pk):
        post = get_object_or_404(self.model, pk=pk)
        form = forms.CommentForm()
        context = {'post':post,
                   'form':form}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        post = get_object_or_404(self.model, pk=pk)
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            form.instance.owner = request.user
            form = form.save()
            post.comment.add(form)
            # alternative way
            # comment = form.save(commit=False)
            # comment.owner = request.user
            # comment.post = post
            # comment.save()
            return redirect('blog:post_detail', pk=pk)
        context = {'post': post,
                   'form': form}
        return render(request, self.template_name, context)


class EditPostView(UserPassesTestMixin, UpdateView):
    model = Post
    form_class = forms.CreateUpdatePost
    template_name = None

    def test_func(self):
        post = self.get_object()
        return True if post.author == self.request.user else False


class DeletePostView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:homes')
    def test_func(self):
        post = self.get_object()
        return True if post.author == self.request.user else False


class CreatePostView(LoginRequiredMixin, CreateView):
    form_class = forms.CreateUpdatePost
    model = Post

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ContactView(LoginRequiredMixin, ListView):
    def get(self, req):
        return render(req, 'home/contact.html')

blog/templates/home/about.html
{% extends 'home/base.html' %}
{% block content %}
    {%  load static %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'home/assets/img/contact-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>

{% endblock content %}

blog/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                {#                todo: make the href work #}
                <a class="navbar-brand" href="#">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                {#                todo: make the href's work #}

                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contact' %}">Contact</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:create_post' %}">Create</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:logout' %}">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:login' %}">Login</a></li>
                        {%  endif %}
                    </ul>
                </div>
            </div>
        </nav>


    {% block content %} {% endblock content %}


        <!-- footer -->

        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Abey's Blog 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
            {% block additional_js %}
        {% endblock additional_js %}
    </body>
</html>

blog/templates/home/contact.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'home/assets/img/contact-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>


        {% block additional_js %}
            <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        {% endblock additional_js %}

{%  endblock content %}

blog/templates/home/create-post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        <!-- page content -->
        <header class="masthead" style="background-image: url('#')">
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                  <div class="page-heading">
                        <h1>Create Form</h1>
                    <span class="subheading">You're going to make a great blog post!</span>
                  </div>
                </div>
              </div>
            </div>
          </header>
        
          <div class="container">
            <div class="row">
              <div class="col-lg-8 col-md-10 mx-auto">
               <!-- form goes here--> 
              </div>
            </div>
          </div>
        
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/home/index.html
{% extends 'home/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'home/assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {%  if post_list %}
                    {%  for post in post_list %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:post_detail' post.id %}">
                            <h2 class="post-title">{{ post.title }}</h2>
                            <h3 class="post-subtitle">{{ post.title }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{ post.author}}</a>
                            {{ post.created_at|naturaltime }}
                        </p>
                    </div>
                    {% endfor %}
                        {%  else %}
                        <p><a href="{% url 'blog:create_post' %}">Add instead</a></p>
                    {% endif %}
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>


{% endblock content %}

blog/templates/home/login.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
{% load crispy_forms_tags %}

  <!-- Page content -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Log In</h1>
            <span class="subheading">Welcome Back!</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div>
        <!-- flash messages goes here-->
       <ul>
        {% for message in messages %}
        <li style="list-style:none; color:red; margin:2% 25%">
          {{ message }}
        </li>
        {% endfor %}
      </ul> -->
    </div>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto content">
        <!-- forms goes here -->
          <form method="post">
              {% csrf_token %}
              {{ form | crispy }}
              <button class = 'btn btn-primary mb-5 mt-3'>Login</button>
          </form>
         <p> Don't have account?
          <a href="{% url 'blog:register' %}"> Register Instead</a>
         </p>

      </div>
    </div>
  </div>

  
{% endblock content %}

blog/templates/home/post.html
{% extends 'home/base.html' %}
{%  load static %}
{% load crispy_forms_tags %}
{% load gravatar_app %}
{% block content %}

        <!-- Page Header-->
        <header class="masthead" style="background-image:url({{ post.image.url }})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ post.title }}</h1>
                            <h2 class="subheading">{{ post.title }}</h2>
                            <span class="meta">
                                Posted by
                                <a href="#">{{ post.author }}</a>
                                on {{  post.created_at }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                       {{ post.description| safe }}
                                </div>
        </div>

          <div class="col-lg-8 col-md-10 mx-5 px-4 mb-5 comment  ">
              {% if post.comment.all   %}
              <ul class="commentList" style="list-style-type: none">
                  {% for cmt in post.comment.all %}
                <li class="row my-4">
                    <div class="commenterImage col-2 pt-2">
{#                              gravatar image #}
                      <img src="{{ cmt.owner | gravatar:60 }}  " class="rounded-pill"/>
                    </div>
                    <div class="commentText col-10 ">
                      <p style="margin: 0; padding: 0;">{{ cmt.body | safe}}</p>
                      <span class="date sub-text">{{cmt.owner.username }}</span>
                    </div>
                </li>
                  {% endfor %}
               </ul>
                  {% endif %}
        </div>
          <div class="mt-5">
              <form method="post" class="mx-5 px-5">
                  {% csrf_token %}
                  {{ form| crispy }}
                  <button class="btn btn-primary">Add comment</button>
              </form>
      </div>
                            {% if request.user == post.author %}
                 <div class="mt-3 mx-5 px-5 mt-5">
                            <a class="btn btn-primary float-right" href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
                            <a class="btn btn-danger float-end" href="delete">Delete</a>
                            </div>
                        {%  endif %}
            </div>
        </article>



{% endblock content %}